name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -c "import sys; print(sys.version)"
    - name: generate data
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
    - name: build frontend
      run: |
        npm install
        npm run build
    - name: publish to netlify cli
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=site --functions=functions
      env:
        NETLIFY_AUTH_TOKEN: 99912a397e5f123f23b663e1b134e380ef4adc340bdc46ba7c156b3e9e65ccc3
        NETLIFY_SITE_ID: 99415dda-6c56-481d-85b4-83ba9a496b3b
